# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
  - main
pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'EventsService'
      repository: 'EventsContainer'
      command: 'buildAndPush'
      Dockerfile: '**/src/Events.API/Dockerfile'