# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mongodb:
    image : mongo:latest
    networks:
        - agendacultural_project   
    container_name: mongodbagendaculturalVM
    volumes:
        - mongodatabase:/data/db
    ports:
        - 27017:27017
    restart: unless-stopped
  eventsapi: 
    image: agendaculturalcontainerregistry.azurecr.io/eventsapi:latest
    networks:
        - agendacultural_project 
    container_name: eventsapiVM
    ports:
        - 5000:5000
    depends_on:
            - mongodb
  agendacultural:
    image: agendaculturalcontainerregistry.azurecr.io/reactagenda:1.0
    container_name: eventsREACTVM
    ports:
      - 3000:3000
volumes:
  mongodatabase:
networks:
    agendacultural_project: 
      
